<?php
// generate_image.php - توليد صورة جاهزة باستخدام GD (بدون حاجة لمفتاح API)
// إذا وُجد مفتاح OpenAI فسيستخدم DALL-E، وإلا سينشئ صورة ديناميكية محلية.

function generateAdImage($prompt) {
    $api_key = OPENAI_API_KEY;
    
    // إذا كان المفتاح حقيقياً، حاول استخدام DALL-E
    if ($api_key !== 'YOUR_OPENAI_API_KEY') {
        $dalle_url = callDalle($api_key, $prompt);
        if ($dalle_url) return $dalle_url;
    }
    
    // إنشاء صورة محلية باستخدام GD مع كتابة النص التعريفي
    return createLocalGDImage($prompt);
}

function callDalle($api_key, $prompt) {
    $data = [
        'model' => 'dall-e-3',
        'prompt' => $prompt . " clean, professional ad, no text overlay, high quality, vibrant colors",
        'n' => 1,
        'size' => '1024x1024',
        'quality' => 'standard'
    ];
    
    $ch = curl_init('https://api.openai.com/v1/images/generations');
    curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
    curl_setopt($ch, CURLOPT_POST, true);
    curl_setopt($ch, CURLOPT_HTTPHEADER, [
        'Authorization: Bearer ' . $api_key,
        'Content-Type: application/json'
    ]);
    curl_setopt($ch, CURLOPT_POSTFIELDS, json_encode($data));
    $response = curl_exec($ch);
    $http = curl_getinfo($ch, CURLINFO_HTTP_CODE);
    curl_close($ch);
    
    if ($http == 200) {
        $res = json_decode($response, true);
        return $res['data'][0]['url'] ?? null;
    }
    return null;
}

function createLocalGDImage($prompt) {
    // إنشاء صورة بحجم 800x600
    $width = 800;
    $height = 600;
    $img = imagecreatetruecolor($width, $height);
    
    // خلفية متدرجة (أزرق سماوي إلى بنفسجي فاتح)
    $color1 = imagecolorallocate($img, 52, 152, 219);   // أزرق
    $color2 = imagecolorallocate($img, 155, 89, 182);   // بنفسجي
    imagefilledrectangle($img, 0, 0, $width, $height, $color1);
    // تدرج بسيط (تأثير خطي)
    for ($i = 0; $i <= $height; $i++) {
        $ratio = $i / $height;
        $r = 52 + (155 - 52) * $ratio;
        $g = 152 + (89 - 152) * $ratio;
        $b = 219 + (182 - 219) * $ratio;
        $col = imagecolorallocate($img, $r, $g, $b);
        imageline($img, 0, $i, $width, $i, $col);
    }
    
    // إضافة شكل هندسي (دائرة خفيفة)
    $light = imagecolorallocatealpha($img, 255, 255, 255, 60);
    imagefilledellipse($img, $width-100, 100, 200, 200, $light);
    imagefilledellipse($img, 100, $height-100, 250, 250, $light);
    
    // كتابة النص المستخلص من الـ prompt
    $text = "AI Generated Ad\n" . (strlen($prompt) > 80 ? substr($prompt, 0, 80) . "..." : $prompt);
    $black = imagecolorallocate($img, 0, 0, 0);
    $white = imagecolorallocate($img, 255, 255, 255);
    
    // مسار الخط (إذا وجد خط النظام، وإلا استخدم خطًا مدمجًا)
    $font_path = "C:/Windows/Fonts/arial.ttf"; // على Windows
    if (!file_exists($font_path)) {
        // محاولة بديلة لمسار خط في XAMPP أو Linux
        $font_path = __DIR__ . "/arial.ttf";
        if (!file_exists($font_path)) {
            // استخدام الخط المدمج (حجم ثابت)
            imagestring($img, 5, 50, $height/2 - 20, $text, $white);
            imagestring($img, 3, 50, $height/2 + 40, "Generated locally - AI Media Buyer", $black);
            return saveAndReturnImage($img);
        }
    }
    
    // كتابة النص باستخدام TTF
    $lines = explode("\n", wordwrap($text, 40, "\n"));
    $y = $height/2 - 30;
    foreach ($lines as $line) {
        imagettftext($img, 18, 0, 50, $y, $white, $font_path, $line);
        $y += 30;
    }
    imagettftext($img, 12, 0, 50, $y+20, $black, $font_path, "Generated by AI Media Buyer - No API key required");
    
    return saveAndReturnImage($img);
}

function saveAndReturnImage($img) {
    // حفظ الصورة في مجلد مؤقت على الخادم وإرجاع رابطها
    $dir = __DIR__ . '/generated_images/';
    if (!is_dir($dir)) mkdir($dir, 0777, true);
    $filename = 'ad_' . uniqid() . '.png';
    $filepath = $dir . $filename;
    imagepng($img, $filepath);
    imagedestroy($img);
    
    // إرجاع رابط URL للصورة (نسبي للموقع)
    return 'generated_images/' . $filename;
}
?>